apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-hostpath
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/db
  storageClassName: local-storage-npk